CREATE TABLE public.relatorio_envios (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    cliente_id uuid,
    contato_id uuid,
    status_envio text,
    viewed boolean DEFAULT false,
    -- Adicionando um campo para o tipo de relatório, que pode ser útil
    tipo_relatorio text,
    -- Adicionando um campo para armazenar o resultado do envio
    resultado_envio jsonb,
    CONSTRAINT relatorio_envios_pkey PRIMARY KEY (id)
    -- As chaves estrangeiras para cliente_id e contato_id serão adicionadas em um passo posterior
    -- para garantir que as tabelas referenciadas existam.
);

-- Habilitar Row Level Security (RLS) para a nova tabela
ALTER TABLE public.relatorio_envios ENABLE ROW LEVEL SECURITY;

-- Comentários para clareza
COMMENT ON TABLE public.relatorio_envios IS 'Tabela para registrar o histórico de envio de relatórios.';
COMMENT ON COLUMN public.relatorio_envios.id IS 'Identificador único do registro de envio.';
COMMENT ON COLUMN public.relatorio_envios.created_at IS 'Data e hora da criação do registro.';
COMMENT ON COLUMN public.relatorio_envios.cliente_id IS 'ID do cliente associado ao relatório (se aplicável).';
COMMENT ON COLUMN public.relatorio_envios.contato_id IS 'ID do contato associado ao relatório (se aplicável).';
COMMENT ON COLUMN public.relatorio_envios.status_envio IS 'Status do envio (ex: "enviado", "falhou", "pendente").';
COMMENT ON COLUMN public.relatorio_envios.viewed IS 'Indica se o relatório foi visualizado.';
COMMENT ON COLUMN public.relatorio_envios.tipo_relatorio IS 'Tipo de relatório enviado (ex: "fatura", "consumo").';
COMMENT ON COLUMN public.relatorio_envios.resultado_envio IS 'Armazena detalhes ou a resposta do processo de envio.';
